### ISSUE TITLE
FlightGear <input> functions

### ISSUE THREAD

**Issue by birkelbach** [makerplane/FIX-Gateway#57]
Right now the FlightGear plugin is only one-way.  FlightGear --> FIX-Gateway.  We need to add the ability to move data from FIX-Gateway to FlightGear as well.

**Comment by neil-d95** [comment]
So Phil the output is fairly simple instead of --socket out it is --socket in with an XML file named I'll need to be a separate file since not everything is needing to be sent to FlightGear. unless you want to do a review but not heading down that path yet.NeilOn March 4, 2019 at 11:27 PM Phil Birkelbach <notifications@github.com> wrote:  Right now the FlightGear plugin is only one-way. FlightGear --> FIX-Gateway. We need to add the ability to move data from FIX-Gateway to FlightGear as well.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by birkelbach** [comment]
I've done some experimenting with it and according to the documentation it can be in the same XML file it's just that the chunks are between <input> tags instead of <output> tags.  It seems like it might not have worked quite the way that it's documented, but it's been a while so I don't remember what issues I had.

**Comment by neil-d95** [comment]
Yeah, you are supposed to be able to use bi instead of in or out but there is a bunch of folks that are having issues using it.

  On March 5, 2019 at 12:15 PM Phil Birkelbach <notifications@github.com> wrote:
 
 
 I've done some experimenting with it and according to the documentation it can be in the same XML file it's just that the chunks are between tags instead of tags. It seems like it might not have worked quite the way that it's documented, but it's been a while so I don't remember what issues I had.

**Comment by birkelbach** [comment]
That was probably it.  I think it works if you use separate --socket arguments right?

**Comment by neil-d95** [comment]
Give it a try I'm out of the area for the next few days.

  On March 5, 2019 at 12:48 PM Phil Birkelbach <notifications@github.com> wrote:
 
 
 That was probably it. I think it works if you use separate --socket arguments right?

**Comment by birkelbach** [comment]
I wrote some cheesy test code into the fgfs plugin and it does work with a separate --generic argument.  I called fgfs like this...

`fgfs --generic=socket,out,10,localhost,5500,udp,fix_fgfs  --generic=socket,in,1,,5501,udp,fix_fgfs`

...and it worked.  I was able to send BARO to FG from FIXGW and receiving the data from FG was still working too.  Now I just need to make it read the configuration, the XML and then act appropriately.
